# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "eksempelklient-etinglysing-altinn"
  tags:
  - "public"
spec:
  type: "documentation"
  lifecycle: "production"
  owner: "digibok"
  system: "grunnbok"
